version: '3.7'
services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ./data/db /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME=admin
      MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - deshee007

  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    environment:
      MONGO_DB_HOSTNAME=mongodb
      MONGO_DB_USERNAME=admin
      MONGO_DB_PASSWORD=admin123
    networks:
      - deshee007
