version: '3'
services:
  node_app:
    container_name: nodeApp
    build: .
    ports:
      - 4000:4000
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db /data/db
