version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./data/db /data/db
